name: Predict Model

# Trigger manually using the "workflow_dispatch" event
on:
  workflow_dispatch:  # Allows you to manually trigger the workflow from the Actions tab

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gdown

    - name: Download Model from Google Drive
      run: |
        gdown 'https://drive.google.com/uc?id=145gmljz5SYogBe9e-UmEC8KKtWk7hQ5q' -O checkpoint.pth

    - name: Run Prediction Script
      run: |
        python predict.py --image_path "assets/Flowers.png" --device "cpu" --topk 5 --output_file "results/prediction_results.txt"
